include_guard(GLOBAL)

set(CPACK_PACKAGE_NAME "YuRadio")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Cross-platform online radio player")
set(CPACK_PACKAGE_VERSION "${YURADIO_VERSION_CANONICAL}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${CPACK_PACKAGE_NAME}")
set(CPACK_PACKAGE_CONTACT "yunag <babushkin.ruslans@gmail.com>")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
